import { InterestListTypes } from "./definitions";

export const interestList: InterestListTypes[] = [
  {
    id: 1,
    name: "Shoes",
    checked: true,
  },
  {
    id: 2,
    name: "Men T-Shirts",
    checked: true,
  },
  {
    id: 3,
    name: "Makeup",
    checked: false,
  },
];

export const usersList: any = [
  {
    id: 1,
    name: "Guest User",
    email: "guest@user.com",
    password: "guestUser123",
  },
  {
    id: 2,
    name: "John Doe",
    username: "john@doe.in",
    password: "johnDoe123",
  },
];
export const categories = [
  { id: 1, categoryName: "Shoes", checked: true },
  { id: 2, categoryName: "T shirts", checked: false },
  { id: 3, categoryName: "Sarees", checked: true },
  { id: 4, categoryName: "Kurtas", checked: false },
  { id: 5, categoryName: "Traditionals", checked: true },
  { id: 6, categoryName: "Mobile", checked: false },
  { id: 7, categoryName: "Laptops", checked: true },
  { id: 8, categoryName: "Watches", checked: false },
  { id: 9, categoryName: "Headphones", checked: true },
  { id: 10, categoryName: "Backpacks", checked: false },
  { id: 11, categoryName: "Cameras", checked: true },
  { id: 12, categoryName: "Perfumes", checked: false },
  { id: 13, categoryName: "Jewelry", checked: true },
  { id: 14, categoryName: "Sunglasses", checked: false },
  { id: 15, categoryName: "Cosmetics", checked: true },
  { id: 16, categoryName: "Handbags", checked: false },
  { id: 17, categoryName: "Books", checked: true },
  { id: 18, categoryName: "Music", checked: false },
  { id: 19, categoryName: "Movies", checked: true },
  { id: 20, categoryName: "Gaming", checked: false },
  { id: 21, categoryName: "Fitness", checked: true },
  { id: 22, categoryName: "Home Decor", checked: false },
  { id: 23, categoryName: "Kitchen Appliances", checked: true },
  { id: 24, categoryName: "Furniture", checked: false },
  { id: 25, categoryName: "Gardening", checked: true },
  { id: 26, categoryName: "Tools", checked: false },
  { id: 27, categoryName: "Art Supplies", checked: true },
  { id: 28, categoryName: "Crafts", checked: false },
  { id: 29, categoryName: "Party Supplies", checked: true },
  { id: 30, categoryName: "Stationery", checked: false },
  { id: 31, categoryName: "Pet Supplies", checked: true },
  { id: 32, categoryName: "Baby Products", checked: false },
  { id: 33, categoryName: "Toys", checked: true },
  { id: 34, categoryName: "Sporting Goods", checked: false },
  { id: 35, categoryName: "Outdoor Equipment", checked: true },
  { id: 36, categoryName: "Travel Accessories", checked: false },
  { id: 37, categoryName: "Fitness Equipment", checked: true },
  { id: 38, categoryName: "Cycling Gear", checked: false },
  { id: 39, categoryName: "Swimwear", checked: true },
  { id: 40, categoryName: "Luggage", checked: false },
  { id: 41, categoryName: "Electronics", checked: true },
  { id: 42, categoryName: "Home Appliances", checked: false },
  { id: 43, categoryName: "Smart Home Devices", checked: true },
  { id: 44, categoryName: "Computers", checked: false },
  { id: 45, categoryName: "Tablets", checked: true },
  { id: 46, categoryName: "Printers", checked: false },
  { id: 47, categoryName: "Monitors", checked: true },
  { id: 48, categoryName: "Networking", checked: false },
  { id: 49, categoryName: "Software", checked: true },
  { id: 50, categoryName: "Office Supplies", checked: false },
  { id: 51, categoryName: "Fishing Gear", checked: true },
  { id: 52, categoryName: "Camping Gear", checked: false },
  { id: 53, categoryName: "Hiking Gear", checked: true },
  { id: 54, categoryName: "Outdoor Clothing", checked: false },
  { id: 55, categoryName: "Climbing Gear", checked: true },
  { id: 56, categoryName: "Water Sports Equipment", checked: false },
  { id: 57, categoryName: "Snow Sports Equipment", checked: true },
  { id: 58, categoryName: "Golf Equipment", checked: false },
  { id: 59, categoryName: "Team Sports Equipment", checked: true },
  { id: 60, categoryName: "Exercise Machines", checked: false },
  { id: 61, categoryName: "Yoga Accessories", checked: true },
  { id: 62, categoryName: "Boxing Gear", checked: false },
  { id: 63, categoryName: "Martial Arts Equipment", checked: true },
  { id: 64, categoryName: "Tennis Equipment", checked: false },
  { id: 65, categoryName: "Soccer Equipment", checked: true },
  { id: 66, categoryName: "Basketball Equipment", checked: false },
  { id: 67, categoryName: "Baseball Equipment", checked: true },
  { id: 68, categoryName: "Softball Equipment", checked: false },
  { id: 69, categoryName: "Gymnastics Equipment", checked: true },
  { id: 70, categoryName: "Volleyball Equipment", checked: false },
  { id: 71, categoryName: "Rugby Equipment", checked: true },
  { id: 72, categoryName: "Cricket Equipment", checked: false },
  { id: 73, categoryName: "Hockey Equipment", checked: true },
  { id: 74, categoryName: "Skateboarding Gear", checked: false },
  { id: 75, categoryName: "Surfing Gear", checked: true },
  { id: 76, categoryName: "Snowboarding Gear", checked: false },
  { id: 77, categoryName: "Skiing Gear", checked: true },
  { id: 78, categoryName: "Inline Skating Gear", checked: false },
  { id: 79, categoryName: "Motorcycle Gear", checked: true },
  { id: 80, categoryName: "Cycling Gear", checked: false },
  { id: 81, categoryName: "Car Accessories", checked: true },
  { id: 82, categoryName: "Truck Accessories", checked: false },
  { id: 83, categoryName: "SUV Accessories", checked: true },
  { id: 84, categoryName: "RV Accessories", checked: false },
  { id: 85, categoryName: "Motorcycle Accessories", checked: true },
  { id: 86, categoryName: "Boating Accessories", checked: false },
  { id: 87, categoryName: "ATV Accessories", checked: true },
  { id: 88, categoryName: "UTV Accessories", checked: false },
  { id: 89, categoryName: "Snowmobile Accessories", checked: true },
  { id: 90, categoryName: "Jet Ski Accessories", checked: false },
  { id: 91, categoryName: "Golf Cart Accessories", checked: true },
  { id: 92, categoryName: "Bicycle Accessories", checked: false },
  { id: 93, categoryName: "Water Sports Accessories", checked: true },
  { id: 94, categoryName: "Snow Sports Accessories", checked: false },
  { id: 95, categoryName: "Camping Accessories", checked: true },
  { id: 96, categoryName: "Hiking Accessories", checked: false },
  { id: 97, categoryName: "Outdoor Accessories", checked: true },
  { id: 98, categoryName: "Exercise Accessories", checked: false },
  { id: 99, categoryName: "Yoga Accessories", checked: true },
  { id: 100, categoryName: "Fitness Accessories", checked: false },
];


